[package]
name = "rhai-env"
version = "0.1.0"
edition = "2021"
authors = ["José F. Rives"]
description = "Read and write env variables in rhai"
keywords = ["scripting", "scripting-language", "embedded", "rhai"]

[dependencies]
rhai = { version = "1.9.1" }
